apiVersion: v1
kind: Service
metadata:
  name: bandera-swagger-docs-service
spec:
  type: NodePort
  selector:
    app: java-app  
  ports:
    - protocol: TCP
      port: 8085         
      targetPort: 8080  
      nodePort: 30085    
