apiVersion: apps/v1
kind: Deployment
metadata:
  name: umeet-service-deployment
  namespace: bandera-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: {{ .Values.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://192.168.49.1:27017/uMeet-service-mongo"
